<?php declare(strict_types=1);

/**
 * API Tejidos Artesanales
 * API para sistema de gestión de productos y servicios de tejidos artesanales
 * PHP version 8.1
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: soporte@tejidosartesanales.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Source files are located at:
 *
 * > https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/php-laravel/
 */


namespace OpenAPI\Server\Api;


interface ProductosApiInterface {


    /**
     * Operation getAllItems
     *
     * Listar todos los productos
     * @param null | int $page
     * @param null | int $limit
     * @return \OpenAPI\Server\Model\GetAllItems200Response | \OpenAPI\Server\Model\Error
     */
    public function getAllItems(
            ?int $page,
            ?int $limit,
    ):
        \OpenAPI\Server\Model\GetAllItems200Response | 
        \OpenAPI\Server\Model\Error
    ;


    /**
     * Operation getItemBySku
     *
     * Obtener producto específico
     * @param int $sku
     * @return \OpenAPI\Server\Model\ItemWithDetails | \OpenAPI\Server\Model\Error
     */
    public function getItemBySku(
            int $sku,
    ):
        \OpenAPI\Server\Model\ItemWithDetails | 
        \OpenAPI\Server\Model\Error
    ;

}
