/* tslint:disable */
/* eslint-disable */
/**
 * API Tejidos Artesanales
 * API para sistema de gestión de productos y servicios de tejidos artesanales 
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: soporte@tejidosartesanales.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

