<?php declare(strict_types=1);

/**
 * API Tejidos Artesanales
 * API para sistema de gestión de productos y servicios de tejidos artesanales
 * PHP version 8.1
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: soporte@tejidosartesanales.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Source files are located at:
 *
 * > https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/php-laravel/
 */


/**
 * InventoryWithDetails
 */
namespace OpenAPI\Server\Model;

/**
 * InventoryWithDetails
 */
use Crell\Serde\Renaming\Cases;
use Crell\Serde\Attributes as Serde;

#[Serde\ClassSettings(renameWith: Cases::snake_case)]
class InventoryWithDetails
{
    /**
    *
    * 
    * @param int $id
    *
    * 
    * @param float $price
    *
    * 
    * @param \OpenAPI\Server\Model\Size $size
    *
    * 
    * @param \OpenAPI\Server\Model\Color $color
    */

    public function __construct(
        public int $id,
        public float $price,
        public \OpenAPI\Server\Model\Size $size,
        public \OpenAPI\Server\Model\Color $color,
    ) {}
}

