<?php declare(strict_types=1);

/**
 * API Tejidos Artesanales
 * API para sistema de gestión de productos y servicios de tejidos artesanales
 * PHP version 8.1
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: soporte@tejidosartesanales.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Source files are located at:
 *
 * > https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/php-laravel/
 */


/**
 * Item
 */
namespace OpenAPI\Server\Model;

/**
 * Item
 */
use Crell\Serde\Renaming\Cases;
use Crell\Serde\Attributes as Serde;

#[Serde\ClassSettings(renameWith: Cases::snake_case)]
class Item
{
    /**
    *
    * 
    * @param int $sku
    *
    * 
    * @param string $title
    *
    * 
    * @param string $description
    *
    * 
    * @param \OpenAPI\Server\Model\ItemStatus $status
    */

    public function __construct(
        public int $sku,
        public string $title,
        public string $description,
        public \OpenAPI\Server\Model\ItemStatus $status,
    ) {}
}

