<?php declare(strict_types=1);

/**
 * API Tejidos Artesanales
 * API para sistema de gestión de productos y servicios de tejidos artesanales
 * PHP version 8.1
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: soporte@tejidosartesanales.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Source files are located at:
 *
 * > https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/php-laravel/
 */


/**
 * ItemStatus
 */
namespace OpenAPI\Server\Model;

/**
 * ItemStatus
 */
enum ItemStatus: string
{
        case ACTIVE = 'active';
        case INACTIVE = 'inactive';
}
