<?php declare(strict_types=1);

/**
 * API Tejidos Artesanales
 * API para sistema de gestión de productos y servicios de tejidos artesanales
 * PHP version 8.1
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: soporte@tejidosartesanales.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Source files are located at:
 *
 * > https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/php-laravel/
 */


namespace OpenAPI\Server\Http\Controllers;

use Crell\Serde\SerdeCommon;
use Illuminate\Routing\Controller;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;


use OpenAPI\Server\Api\ProductosApiInterface;

class ProductosController extends Controller
{
    /**
     * Constructor
     */
    public function __construct(
        private readonly ProductosApiInterface $api,
        private readonly SerdeCommon $serde = new SerdeCommon(),
    )
    {
    }

    /**
     * Operation getAllItems
     *
     * Listar todos los productos.
     *
     */
    public function getAllItems(Request $request): JsonResponse
    {
        $validator = Validator::make(
            array_merge(
                [
                    
                ],
                $request->all(),
            ),
            [
                'page' => [
                    'integer',
                ],
                'limit' => [
                    'integer',
                ],
            ],
        );

        if ($validator->fails()) {
            return response()->json(['error' => 'Invalid input'], 400);
        }

        $page = $request->integer('page');

        $limit = $request->integer('limit');

        try {
            $apiResult = $this->api->getAllItems($page, $limit);
        } catch (\Exception $exception) {
            // This shouldn't happen
            report($exception);
            return response()->json(['error' => $exception->getMessage()], 500);
        }

        if ($apiResult instanceof \OpenAPI\Server\Model\GetAllItems200Response) {
            return response()->json($this->serde->serialize($apiResult, format: 'array'), 200);
        }

        if ($apiResult instanceof \OpenAPI\Server\Model\Error) {
            return response()->json($this->serde->serialize($apiResult, format: 'array'), 500);
        }


        // This shouldn't happen
        return response()->abort(500);
    }
    /**
     * Operation getItemBySku
     *
     * Obtener producto específico.
     *
     */
    public function getItemBySku(Request $request, int $sku): JsonResponse
    {
        $validator = Validator::make(
            array_merge(
                [
                    'sku' => $sku,
                ],
                $request->all(),
            ),
            [
                'sku' => [
                    'required',
                    'integer',
                ],
            ],
        );

        if ($validator->fails()) {
            return response()->json(['error' => 'Invalid input'], 400);
        }


        try {
            $apiResult = $this->api->getItemBySku($sku);
        } catch (\Exception $exception) {
            // This shouldn't happen
            report($exception);
            return response()->json(['error' => $exception->getMessage()], 500);
        }

        if ($apiResult instanceof \OpenAPI\Server\Model\ItemWithDetails) {
            return response()->json($this->serde->serialize($apiResult, format: 'array'), 200);
        }

        if ($apiResult instanceof \OpenAPI\Server\Model\Error) {
            return response()->json($this->serde->serialize($apiResult, format: 'array'), 404);
        }


        // This shouldn't happen
        return response()->abort(500);
    }
}
