<?php declare(strict_types=1);

/**
 * API Tejidos Artesanales
 * API para sistema de gestión de productos y servicios de tejidos artesanales
 * PHP version 8.1
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: soporte@tejidosartesanales.com
 *
 * NOTE: This class is auto generated by OpenAPI-Generator
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 * Source files are located at:
 *
 * > https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/php-laravel/
 */


use Illuminate\Support\Facades\Route;

/**
 * GET getItemInventory
 * Summary: Listar variantes de inventario
 * Notes: 
 */
Route::GET('/v1/items/{sku}/inventory', [\OpenAPI\Server\Http\Controllers\InventarioController::class, 'getItemInventory'])->name('inventario.get.item.inventory');

/**
 * GET getAllItems
 * Summary: Listar todos los productos
 * Notes: 
 */
Route::GET('/v1/items', [\OpenAPI\Server\Http\Controllers\ProductosController::class, 'getAllItems'])->name('productos.get.all.items');

/**
 * GET getItemBySku
 * Summary: Obtener producto específico
 * Notes: 
 */
Route::GET('/v1/items/{sku}', [\OpenAPI\Server\Http\Controllers\ProductosController::class, 'getItemBySku'])->name('productos.get.item.by.sku');

